services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=devicedb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'TZ=UTC'
      - 'PGTZ=UTC'
    ports:
      - '5432:5432'
