SET TIME ZONE 'UTC';

ALTER TYPE device_state RENAME VALUE 'available' TO 'AVAILABLE';
ALTER TYPE device_state RENAME VALUE 'in-use' TO 'IN_USE';
ALTER TYPE device_state RENAME VALUE 'inactive' TO 'INACTIVE';

ALTER TABLE devices
    ALTER COLUMN state SET DEFAULT 'INACTIVE',
    ALTER COLUMN creation_time TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN update_time TYPE TIMESTAMP WITH TIME ZONE;
